//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.05 at 12:04:53 PM GST 
//


package com.maintainapps.module.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for documentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outlinks" type="{http://bayan.ir}outlinksType" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="fragment" type="{http://bayan.ir}fragmentType" minOccurs="0"/>
 *           &lt;element name="extract-to" type="{http://bayan.ir}extractToType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contentType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inherits" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="engine" type="{http://www.w3.org/2001/XMLSchema}string" default="css" />
 *       &lt;attribute name="root" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="update" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="every" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adaptive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="stopProcessing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentType", propOrder = {
    "outlinks",
    "fragmentOrExtractTo"
})
public class DocumentType {

    protected OutlinksType outlinks;
    @XmlElements({
        @XmlElement(name = "fragment", type = FragmentType.class),
        @XmlElement(name = "extract-to", type = ExtractToType.class)
    })
    protected List<Object> fragmentOrExtractTo;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "url")
    protected String url;
    @XmlAttribute(name = "contentType")
    protected String contentType;
    @XmlAttribute(name = "ip")
    protected String ip;
    @XmlAttribute(name = "inherits")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object inherits;
    @XmlAttribute(name = "engine")
    protected String engine;
    @XmlAttribute(name = "root")
    protected String root;
    @XmlAttribute(name = "update")
    protected Boolean update;
    @XmlAttribute(name = "every")
    protected String every;
    @XmlAttribute(name = "adaptive")
    protected Boolean adaptive;
    @XmlAttribute(name = "stopProcessing")
    protected Boolean stopProcessing;

    /**
     * Gets the value of the outlinks property.
     * 
     * @return
     *     possible object is
     *     {@link OutlinksType }
     *     
     */
    public OutlinksType getOutlinks() {
        return outlinks;
    }

    /**
     * Sets the value of the outlinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutlinksType }
     *     
     */
    public void setOutlinks(OutlinksType value) {
        this.outlinks = value;
    }

    /**
     * Gets the value of the fragmentOrExtractTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fragmentOrExtractTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFragmentOrExtractTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FragmentType }
     * {@link ExtractToType }
     * 
     * 
     */
    public List<Object> getFragmentOrExtractTo() {
        if (fragmentOrExtractTo == null) {
            fragmentOrExtractTo = new ArrayList<Object>();
        }
        return this.fragmentOrExtractTo;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIp() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIp(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the inherits property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInherits() {
        return inherits;
    }

    /**
     * Sets the value of the inherits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInherits(Object value) {
        this.inherits = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngine() {
        if (engine == null) {
            return "css";
        } else {
            return engine;
        }
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngine(String value) {
        this.engine = value;
    }

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoot(String value) {
        this.root = value;
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUpdate() {
        if (update == null) {
            return false;
        } else {
            return update;
        }
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdate(Boolean value) {
        this.update = value;
    }

    /**
     * Gets the value of the every property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvery() {
        return every;
    }

    /**
     * Sets the value of the every property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvery(String value) {
        this.every = value;
    }

    /**
     * Gets the value of the adaptive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAdaptive() {
        if (adaptive == null) {
            return true;
        } else {
            return adaptive;
        }
    }

    /**
     * Sets the value of the adaptive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdaptive(Boolean value) {
        this.adaptive = value;
    }

    /**
     * Gets the value of the stopProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStopProcessing() {
        if (stopProcessing == null) {
            return false;
        } else {
            return stopProcessing;
        }
    }

    /**
     * Sets the value of the stopProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStopProcessing(Boolean value) {
        this.stopProcessing = value;
    }

}
