//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.05 at 12:04:53 PM GST 
//


package com.maintainapps.module.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fragmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fragmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outlinks" type="{http://bayan.ir}outlinksType" minOccurs="0"/>
 *         &lt;element name="extract-to" type="{http://bayan.ir}extractToType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="root" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fragmentType", propOrder = {
    "outlinks",
    "extractTo"
})
public class FragmentType {

    protected OutlinksType outlinks;
    @XmlElement(name = "extract-to")
    protected List<ExtractToType> extractTo;
    @XmlAttribute(name = "root")
    protected String root;

    /**
     * Gets the value of the outlinks property.
     * 
     * @return
     *     possible object is
     *     {@link OutlinksType }
     *     
     */
    public OutlinksType getOutlinks() {
        return outlinks;
    }

    /**
     * Sets the value of the outlinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutlinksType }
     *     
     */
    public void setOutlinks(OutlinksType value) {
        this.outlinks = value;
    }

    /**
     * Gets the value of the extractTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extractTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtractTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtractToType }
     * 
     * 
     */
    public List<ExtractToType> getExtractTo() {
        if (extractTo == null) {
            extractTo = new ArrayList<ExtractToType>();
        }
        return this.extractTo;
    }

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoot(String value) {
        this.root = value;
    }

}
