//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.05 at 12:04:53 PM GST 
//


package com.maintainapps.module.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for outlinksType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outlinksType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="link" type="{http://bayan.ir}linkType" minOccurs="0"/>
 *           &lt;element name="for-each" type="{http://bayan.ir}forEachType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outlinksType", propOrder = {
    "linkOrForEach"
})
public class OutlinksType {

    @XmlElements({
        @XmlElement(name = "link", type = LinkType.class),
        @XmlElement(name = "for-each", type = ForEachType.class)
    })
    protected List<Object> linkOrForEach;

    /**
     * Gets the value of the linkOrForEach property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkOrForEach property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkOrForEach().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkType }
     * {@link ForEachType }
     * 
     * 
     */
    public List<Object> getLinkOrForEach() {
        if (linkOrForEach == null) {
            linkOrForEach = new ArrayList<Object>();
        }
        return this.linkOrForEach;
    }

}
