//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.05 at 12:04:53 PM GST 
//


package com.maintainapps.module.schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Truncates a string if its size is greater than max. In this case, it appends, the specified append string to the result
 * 			
 * 
 * <p>Java class for truncateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="truncateType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bayan.ir}singleFunctionType">
 *       &lt;attribute name="max" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="append" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="breakOnWhitespaces" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "truncateType")
public class TruncateType
    extends SingleFunctionType
{

    @XmlAttribute(name = "max", required = true)
    protected BigInteger max;
    @XmlAttribute(name = "append")
    protected String append;
    @XmlAttribute(name = "breakOnWhitespaces")
    protected Boolean breakOnWhitespaces;

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMax(BigInteger value) {
        this.max = value;
    }

    /**
     * Gets the value of the append property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppend() {
        return append;
    }

    /**
     * Sets the value of the append property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppend(String value) {
        this.append = value;
    }

    /**
     * Gets the value of the breakOnWhitespaces property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBreakOnWhitespaces() {
        if (breakOnWhitespaces == null) {
            return false;
        } else {
            return breakOnWhitespaces;
        }
    }

    /**
     * Sets the value of the breakOnWhitespaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBreakOnWhitespaces(Boolean value) {
        this.breakOnWhitespaces = value;
    }

}
